/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.Calendar;
import java.util.TimeZone;

class LibraryTest {
    private ZonedDateTime currentTime;
    private long currentTimeEpochMillis;

    public static Calendar fromZonedDateTime(ZonedDateTime zonedDateTime) {
        Calendar calendar = Calendar.getInstance(TimeZone.getTimeZone(zonedDateTime.getZone()));
        calendar.setTimeInMillis(zonedDateTime.toInstant().toEpochMilli());
        return calendar;
    }

    public static String formatTime(Calendar date) {
        return String.format("Default: [%s] UTC: [%s]", date.getTime(), java.time.Instant.ofEpochMilli(date.getTimeInMillis()));
    }

    public static String formatTimeUTC(Calendar date) {
        return String.format("[%s]", java.time.Instant.ofEpochMilli(date.getTimeInMillis()));
    }

    @BeforeEach
    void setUp() {
        currentTime = ZonedDateTime.of(2026, 2, 23, 10, 0, 0, 0,
                ZoneId.of("Australia/Victoria"));
        currentTimeEpochMillis = fromZonedDateTime(currentTime).getTimeInMillis();
    }

    @Test
    void test() {
        final Calendar intervalStart = fromZonedDateTime(currentTime);
        intervalStart.setTimeZone(TimeZone.getTimeZone("Australia/Victoria"));
        intervalStart.setTimeInMillis(currentTimeEpochMillis);
        intervalStart.set(Calendar.HOUR_OF_DAY, 13);
        intervalStart.set(Calendar.MINUTE, 0);
        intervalStart.set(Calendar.SECOND, 0);
        intervalStart.set(Calendar.MILLISECOND, 0);

        final Calendar intervalEnd = fromZonedDateTime(currentTime);
        intervalEnd.setTimeZone(TimeZone.getTimeZone("America/New_York"));
        intervalEnd.setTimeInMillis(currentTimeEpochMillis);
        intervalEnd.set(Calendar.HOUR_OF_DAY, 17);
        intervalEnd.set(Calendar.MINUTE, 0);
        intervalEnd.set(Calendar.SECOND, 0);
        intervalEnd.set(Calendar.MILLISECOND, 0);

        System.out.println("Before change DAY_OF_WEEK to Sunday " + formatTime(intervalStart));
        intervalStart.set(Calendar.DAY_OF_WEEK, Calendar.SUNDAY);
        System.out.println("After change DAY_OF_WEEK to Sunday " + formatTime(intervalStart));

        if (intervalStart.getTimeInMillis() > currentTimeEpochMillis) {
            System.out.println("Before subtracting WEEK_OF_YEAR by 1 " + intervalStart.getTime());
            intervalStart.add(Calendar.WEEK_OF_YEAR, -1); // MODIFICATION 1
            System.out.println("After subtracting WEEK_OF_YEAR by 1" + intervalStart.getTime());

            System.out.println("Before subtracting WEEK_OF_YEAR by 1 " + formatTime(intervalEnd));
            intervalEnd.add(Calendar.WEEK_OF_YEAR, -1);  // MODIFICATION 2
            System.out.println("After subtracting WEEK_OF_YEAR by 1 " + formatTime(intervalEnd));
        }

        System.out.println("===============================");
        if (intervalEnd.getTimeInMillis() < intervalStart.getTimeInMillis()) {
            intervalEnd.add(Calendar.WEEK_OF_YEAR, 1);
        }

        System.out.println("Before change DAY_OF_WEEK to Saturday " + formatTime(intervalEnd));
        intervalEnd.set(Calendar.DAY_OF_WEEK, Calendar.SATURDAY);
        System.out.println("After change DAY_OF_WEEK to Saturday " + formatTime(intervalEnd));

        if (intervalEnd.getTimeInMillis() <= intervalStart.getTimeInMillis()) {
            System.out.println("Before adding WEEK_OF_MONTH by 1" + intervalEnd.getTime());
            intervalEnd.add(Calendar.WEEK_OF_MONTH, 1);
            System.out.println("After adding WEEK_OF_MONTH by 1" + intervalEnd.getTime());
        }
        System.out.println("Final interval : " + formatTimeUTC(intervalStart) + " TILL " + formatTimeUTC(intervalEnd));

        Assertions.assertTrue(intervalStart.getTimeInMillis() < intervalEnd.getTimeInMillis());
    }


    @Test
    void testSimplify() {
        // this is to mimic behavior of  quickfix.DefaultSessionSchedule#theMostRecentIntervalBefore
        final Calendar intervalStart = fromZonedDateTime(currentTime);
        intervalStart.setTimeZone(TimeZone.getTimeZone("Australia/Victoria"));
        intervalStart.setTimeInMillis(currentTimeEpochMillis);
        intervalStart.set(Calendar.HOUR_OF_DAY, 13);
        intervalStart.set(Calendar.MINUTE, 0);
        intervalStart.set(Calendar.SECOND, 0);
        intervalStart.set(Calendar.MILLISECOND, 0);

        final Calendar intervalEnd = fromZonedDateTime(currentTime);
        intervalEnd.setTimeZone(TimeZone.getTimeZone("America/New_York"));
        intervalEnd.setTimeInMillis(currentTimeEpochMillis);
        intervalEnd.set(Calendar.HOUR_OF_DAY, 17);
        intervalEnd.set(Calendar.MINUTE, 0);
        intervalEnd.set(Calendar.SECOND, 0);
        intervalEnd.set(Calendar.MILLISECOND, 0);

        intervalStart.set(Calendar.DAY_OF_WEEK, Calendar.SUNDAY);
        if (intervalStart.getTimeInMillis() > currentTimeEpochMillis) {
            intervalStart.add(Calendar.WEEK_OF_YEAR, -1);  // MODIFICATION 1
            intervalEnd.add(Calendar.WEEK_OF_YEAR, -1);  // MODIFICATION 2
        }
        if (intervalEnd.getTimeInMillis() < intervalStart.getTimeInMillis()) {
            intervalEnd.add(Calendar.WEEK_OF_YEAR, 1);
        }

        intervalEnd.set(Calendar.DAY_OF_WEEK, Calendar.SATURDAY);
        if (intervalEnd.getTimeInMillis() <= intervalStart.getTimeInMillis()) {
            intervalEnd.add(Calendar.WEEK_OF_MONTH, 1);
        }
        Assertions.assertTrue(intervalStart.getTimeInMillis() < intervalEnd.getTimeInMillis());
        System.out.println("Final interval : " + formatTimeUTC(intervalStart) + " TILL " + formatTimeUTC(intervalEnd));
    }
}
